name: Frontend Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE: stilto_frontend
      DOMAIN: stilto.io
      IMAGE: dh.topg.systems/stilto/stilto_frontend:${{ github.run_number }}
      REPLICAS: 1
      CONTAINER_PORT: 3000
      HOST: ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      PORT: ${{ secrets.SSH_PORT }}
      HEALTH_PATH: /health
      # APP ENV
      NEXT_PUBLIC_WEB3MODAL_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WEB3MODAL_PROJECT_ID }}
      NEXT_PUBLIC_GIPHY_API_KEY: ${{ secrets.NEXT_PUBLIC_GIPHY_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: dh.topg.systems
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          file: ./frontend/Dockerfile
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE }}
          build-args: |
            NEXT_PUBLIC_WEB3MODAL_PROJECT_ID=${{ env.NEXT_PUBLIC_WEB3MODAL_PROJECT_ID }}
            NEXT_PUBLIC_GIPHY_API_KEY=${{ secrets.NEXT_PUBLIC_GIPHY_API_KEY }}
      - name: Add SSH key
        run: |
          sleep 10s
          mkdir -p ~/.ssh/
          ssh-keyscan -p $PORT -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      - name: Deploy service
        env:
          DOMAIN_LABEL: traefik.http.routers.${{ env.SERVICE }}.rule=Host\(\`${{ env.DOMAIN }}\`\)
          HEALTH_URL: http://localhost:${{ env.CONTAINER_PORT }}${{ env.HEALTH_PATH }}
        run: |
          if ssh -p $PORT $HOST "docker service ls --format '{{.Name}}' | grep -q $SERVICE"; then
            echo "Updating service $SERVICE"
            ssh -p $PORT $HOST "docker service update \
              --with-registry-auth --force \
              --image ${{ env.IMAGE }} \
              --env-add NEXT_PUBLIC_WEB3MODAL_PROJECT_ID=${{ env.NEXT_PUBLIC_WEB3MODAL_PROJECT_ID }} \
              --env-add NEXT_PUBLIC_GIPHY_API_KEY=${{ env.NEXT_PUBLIC_GIPHY_API_KEY }} \
              $SERVICE"
          else
            echo "Creating service $SERVICE"
            ssh -p $PORT $HOST "docker service create \
              --with-registry-auth \
              --detach \
              --name $SERVICE \
              --replicas $REPLICAS \
              --update-delay 10s \
              --update-parallelism 1 \
              --update-order start-first \
              --health-cmd 'curl -f $HEALTH_URL || exit 1' \
              --health-interval 5s \
              --health-retries 3 \
              --health-timeout 3s \
              --network web \
              --network regres_db \
              --label traefik.enable=true \
              --label $DOMAIN_LABEL \
              --label traefik.http.routers.$SERVICE.entrypoints=https \
              --label traefik.http.routers.$SERVICE.tls=true \
              --label traefik.http.routers.$SERVICE.service=$SERVICE \
              --label traefik.http.services.$SERVICE.loadbalancer.server.port=$CONTAINER_PORT \
              --env NEXT_PUBLIC_WEB3MODAL_PROJECT_ID=${{ env.NEXT_PUBLIC_WEB3MODAL_PROJECT_ID }} \
              --env NEXT_PUBLIC_GIPHY_API_KEY=${{ env.NEXT_PUBLIC_GIPHY_API_KEY }} \
              $IMAGE"
          fi
